CSV_PATH: "data/pdbbind/pdbbind_ft.csv"
MODEL_NAME: "finetune"
BATCH_SIZE: 64
VAL_BATCH_SIZE: 64
LR: 1e-3
EPOCHS: 100
PROT_DIM: 960
LIG_DIM: 768 
HIDDEN_DIM: 256
NUM_HEADS: 4
MAX_DOMAINS: 10
ESM_PATH: PATH-TO-ESM
NUM_WORKERS: 4
seed: 42
emb_path: "data/pdbbind/embeddings"
pretrained_model_path: "outputs/pretrain_ckpt"

esm_name: 'Synthyra/ESMplusplus_small'
molformer_name: "ibm/MoLFormer-XL-both-10pct"
lora_r: 8
lora_alpha: 16

peft: False
use_amp: bf16
checkpointing: True

evi_reg: True

wandb_project: "finetune"
